/**
 * 
 */
package edu.gvsu.CIS163.Fall_2015.Andrew_Sully.BankingProgram;
import java.io.Serializable;
import java.util.GregorianCalendar;


/***********************************************************************
 * A base account class with several
 * instance variables and getters and setters
 * @author Sully
 **********************************************************************/
public abstract class Account implements Serializable{
    //TODO: Javadoc this variable
	private static final long serialVersionUID = 959565410L;

    /**
     * The character used to separate the values in toString()
     */
    public static final String toStringSeparator = ";";

    /**
     * The unique account number for this account
     */
	private String number;

    /**
     * The name of the owner of this account
     */
	private String owner;

    /**
     * The date that this account was created
     */
	private GregorianCalendar dateOpened;

    /**
     * The current balance of the account
     */
	private double balance;

	public Account() {
        //TODO: Different constructors?

        //Calls to methods to ensure the strings are in valid format
		setNumber("");
		setOwnerName("");

        //TODO: Come up with a better default value
		//dateOpened = "";
		balance = 0;
	}

    /*******************************************************************
     * Set account instance variables based on a dataString
     * @param dataString A string in the format generated by toString()
     * @throws IllegalArgumentException if string is formatted wrongly
     ******************************************************************/
    public abstract void parseFromString(String dataString);

	/*******************************************************************
	 * Gets the account number of this account
	 * @return The account number
	 ******************************************************************/
	public String getNumber() {
		return number;
	}
	
	/*******************************************************************
     * Gets the name of the owner of this account
	 * @return The name of the owner
	 ******************************************************************/
	public String getOwnerName() {
		return owner;
	}
	
	/*******************************************************************
     * Gets the date that the account was opened
	 * @return The date the account was opened
	 ******************************************************************/
	public GregorianCalendar getDateOpened() {
		return dateOpened;
	}
	
	/*******************************************************************
     * Gets the current balance of the account
	 * @return The current balance of the account
	 ******************************************************************/
	public double getBalance() {
		return balance;
	}
	
	/*******************************************************************
     *
	 * @return the serialversionuid
	 ******************************************************************/
	public static long getSerialversionuid() {
		//TODO: Figure out what this does and write javadoc
        return serialVersionUID;
	}
	
	/*******************************************************************
     * Sets the account number
	 * @param number The new account number for this account
	 ******************************************************************/
	public void setNumber(String number) {
        if (number.contains(";"))
            //This would cause conflicts with the toString() output
            throw new IllegalArgumentException();
		this.number = number;
	}

	/*******************************************************************
     * Sets the name of the owner of this account
	 * @param owner The name of the owner
	 ******************************************************************/
	public void setOwnerName(String owner) {
        if (number.contains(";"))
            //This would cause conflicts with the toString() output
            throw new IllegalArgumentException();
        this.owner = owner;
	}

	/*******************************************************************
     * Sets the date that the account was opened
	 * @param dateOpened The date that the account was opened
	 ******************************************************************/
	public void setDateOpened(GregorianCalendar dateOpened) {
		this.dateOpened = dateOpened;
	}

	/*******************************************************************
     * Sets the balance of the account
	 * @param balance The new balance of the account
	 ******************************************************************/
	public void setBalance(double balance) {
		this.balance = balance;
	}

    /*******************************************************************
     * Generates a string representation of this account
     * @return A string in the format:
     *       "ID:NUMBER;NAME;DATE_OPENED;BALANCE;(Any other parameters)"
     ******************************************************************/
    @Override
    public abstract String toString();
}