package edu.gvsu.CIS163.Fall_2015.Andrew_Sully.BankingProgram;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;

import java.io.Serializable;
import java.util.GregorianCalendar;

/***********************************************************************
 * An account that has a minimum balance and an interest rate
 **********************************************************************/
public class SavingsAccount extends Account implements Serializable {
    /**
     * A unique identifier for this class
     */
	private static final long serialVersionUID = 996106642L;

    /**
     * Identifies the class for the toString() method
     */
    public static final String classIdentifier = "SavingsAccount";

    /**
     * The number of items represented in the output of toString()
     */
    private static final int numberOfItemsInToString = 7;

    /**
     * The minimum balance the account must have
     */
	private double minBalance;
    /**
     * The interest rate for this account
     */
	private double interestRate;

    public SavingsAccount() {
        this("","", new GregorianCalendar(), 0);
    }

    public SavingsAccount(String number){
        this(number, "", new GregorianCalendar(), 0);
    }

    public SavingsAccount(String number, String name){
        this(number, name, new GregorianCalendar(), 0);
    }

    public SavingsAccount(String number, String ownerName,
                          double balance){
        this(number, ownerName, new GregorianCalendar(), balance);
    }

    public SavingsAccount(String number, String ownerName,
                          double balance, double minBalance){
        this(number, ownerName, new GregorianCalendar(),
                balance, minBalance);
    }

    public SavingsAccount(String number, String ownerName,
                          double balance, double minBalance,
                          double interestRate){
        this(number, ownerName, new GregorianCalendar(), balance,
                minBalance, interestRate);
    }

    public SavingsAccount(String number, String ownerName,
                   GregorianCalendar dateOpened){
        this(number, ownerName, dateOpened, 0);
    }

    public SavingsAccount(String number, String ownerName,
                   GregorianCalendar dateOpened, double balance){
        this(number, ownerName, dateOpened, balance, 0);
    }

    public SavingsAccount(String number, String ownerName,
                   GregorianCalendar dateOpened, double balance,
                   double minBalance){
        this(number, ownerName, dateOpened, balance, minBalance, 0);
    }

    public SavingsAccount(String number, String ownerName,
                   GregorianCalendar dateOpened, double balance,
                   double minBalance, double interestRate){
        super(number, ownerName, dateOpened, balance);

        setMinBalance(minBalance);
        setInterestRate(interestRate);
    }

    /*******************************************************************
     * Set account instance variables based on a dataString
     * @param dataString A string in the format generated by toString()
     * @throws IllegalArgumentException if string is formatted wrongly
     ******************************************************************/
    @Override
    public void parseFromString(String dataString){
        String[] parsedStrings = dataString.split(toStringSeparator);
        if (parsedStrings.length != numberOfItemsInToString)
            throw new IllegalArgumentException();

        if(!parsedStrings[0].equals(classIdentifier))
            throw new IllegalArgumentException();

        try  {
            //Try to parse out the strings into the various variables
            setNumber(parsedStrings[1]);
            setOwnerName(parsedStrings[2]);
            setDateOpenedInMillis(Long.parseLong(parsedStrings[3]));
            setBalance(Double.parseDouble(parsedStrings[4]));
            setMinBalance(Double.parseDouble(parsedStrings[5]));
            setInterestRate(Double.parseDouble(parsedStrings[6]));
        } catch (NumberFormatException | NullPointerException e){
            //If the numbers weren't right, it's an argument problem
            throw new IllegalArgumentException();
        }
    }

    /*******************************************************************
	 * Gets the minimum required balance for this account
	 * @return the minimum required balance
	 ******************************************************************/
	public double getMinBalance() {
		return minBalance;
	}
	
	/*******************************************************************
     * Gets the interest rate for this account
	 * @return the interest rate for this account
	 ******************************************************************/
	public double getInterestRate() {
		return interestRate;
	}
	
	/*******************************************************************
     * Gets the serial version UID for file identification purposes
	 * @return the serialVersionuid for this class
	 ******************************************************************/
	public static long getSerialversionuid() {
        return serialVersionUID;
	}
	
	/*******************************************************************
     * Sets the minimum balance for this account
	 * @param minBalance the new minimum balance to set
     * @throws IllegalArgumentException if minBalance < this.balance
	 ******************************************************************/
	public void setMinBalance(double minBalance) {
        if (minBalance < getBalance())
            throw new IllegalArgumentException();
		this.minBalance = minBalance;
	}
	
	/*******************************************************************
     * Sets the interest rate for this account
	 * @param interestRate the new interest rate to set
	 ******************************************************************/
	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}


    /*******************************************************************
     * Sets the balance of the account if balance >= this.minBalance
     * @param balance The new balance of the account
     * @throws IllegalArgumentException if balance < this.minBalance
     ******************************************************************/
    @Override
    public void setBalance(double balance){
        if (balance >= this.minBalance){
            super.setBalance(balance);
        } else {
            throw new IllegalArgumentException();
        }
    }

    /*******************************************************************
     * Generates a string representation of this account
     * @return A string in the format:
     *    "ID:NUMBER;NAME;DATE_OPENED;BALANCE;MIN_BALANCE;INTEREST_RATE"
     ******************************************************************/
    @Override
    public String toString(){
        //Hidden toString calls here
        return  classIdentifier + toStringSeparator
                + getNumber() + toStringSeparator
                + getOwnerName() + toStringSeparator
                + getDateOpenedInMillis() + toStringSeparator
                + getBalance() + toStringSeparator
                + getMinBalance() + toStringSeparator
                + getInterestRate();
    }

    /*******************************************************************
     * Generates a DOM element that represents this account
     * @return A DOM element that represents the account
     ******************************************************************/
    @Override
    public Element getDOMNode(Document dom){
        Element root = dom.createElement(classIdentifier);

        Element accNumber = dom.createElement("AccountNumber");
        accNumber.appendChild(dom.createTextNode(getNumber()));
        root.appendChild(accNumber);

        Element ownName = dom.createElement("OwnerName");
        ownName.appendChild(dom.createTextNode(getOwnerName()));
        root.appendChild(ownName);

        Element date = dom.createElement("DateOpened");
        date.appendChild(dom.createTextNode(Long.toString(
                        getDateOpenedInMillis()))
        );
        root.appendChild(date);

        Element balance = dom.createElement("Balance");
        balance.appendChild(dom.createTextNode(Double.toString(
                getBalance()
        )));
        root.appendChild(balance);

        Element minBalance = dom.createElement("MinimumBalance");
        minBalance.appendChild(dom.createTextNode(Double.toString(
                getMinBalance()
        )));
        root.appendChild(minBalance);

        Element interestRate = dom.createElement("InterestRate");
        interestRate.appendChild(dom.createTextNode(Double.toString(
                getInterestRate()
        )));
        root.appendChild(interestRate);

        return root;
    }

    /*******************************************************************
     * Parses an account from a DOM element and sets instance variables
     * @param element The element to parse from
     ******************************************************************/
    @Override
    public void parseFromDOMElement(Element element) {
        //TODO: Implement this method
    }
}